import Head from "next/head";
import Nav from "./Nav";
import Main from "./Main";
import Container from "./Container";

export default function Layout({children}) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Container className="flex min-h-screen">
                <Nav className="flex-1 max-w-xs p-8 border-r"/>

                <Main className="flex-1 p-8">
                    {children}
                </Main>
            </Container>
        </>
    )
}